# [[plugins]]
# repo = 'Shougo/denite.nvim'
#
# [[plugins]]
# repo = 'Shougo/unite.vim'
#
# [[plugins]]
# repo = 'ujihisa/unite-colorscheme'
# on_source = ['unite.vim']
#
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = '''
#   let g:deoplete#enable_at_startup = 1
#   set completeopt+=noinsert
# '''
#
# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
#
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# on_source = ['neosnippet.vim']
#
# [[plugins]]
# repo = 'othree/html5.vim'
# on_ft = ['html','vue']
# hook_add = '''
#   let g:html5_event_handler_attributes_complete = 1
#   let g:html5_rdfa_attributes_complete = 1
#   let g:html5_microdata_attributes_complete = 1
#   let g:html5_aria_attributes_complete = 1
# '''
#
# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']
#
# [[plugins]]
# repo = 'tpope/vim-rails'
# on_ft = ['ruby']
#
# [[plugins]]
# repo = 'alpaca-tc/vim-endwise.git'
# on_ft = ['ruby']
# hook_add = '''
#   let g:endwise_no_mappings=1
# '''
#
# [[plugins]]
# repo = 'jelera/vim-javascript-syntax'
# on_ft = ['javascript']
#
# [[plugins]]
# repo = 'digitaltoad/vim-pug'
# on_ft = ['pug']
#
# [[plugins]]
# repo = 'hail2u/vim-css3-syntax'
# on_ft = ['css','scss','sass']
#
# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
# on_ft = ['css','scss','sass']
#
# [[plugins]]
# repo = 'slim-template/vim-slim'
# on_ft = ['slim']
#
# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue']
#
# [[plugins]]
# repo = 'cespare/vim-toml'
# on_ft = ['toml']
#
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# on_ft = ['markdown']
#
# [[plugins]]
# repo = 'elzr/vim-json'
# hook_add = '''
#   let g:vim_json_syntax_conceal = 0
# '''
# on_ft = ['json']
#
# [[plugins]]
# repo = 'alvan/vim-closetag'
# on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
# hook_add = '''
#   let g:closetag_filenames='*.html'
#   let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
#   let g:closetag_filetypes='html'
#   let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
#   let g:closetag_emptyTags_caseSensitive=1
#   let g:closetag_shortcut='>'
# '''
